# whoami.yml
services:
  # WHOAMI - Path-prefix routed to standard port 80
  whoami:
    image: traefik/whoami
    labels:
      # Traefik-aware
      - "traefik.enable=true"
      # Name-routed from "auth" subdomain
      - "traefik.http.routers.whoami.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.whoami.rule=PathPrefix(`${WHOAMI_PUBLIC_PATH}`)"
      # HTTP/HTTPS Ingress
      - "traefik.http.routers.whoami.entrypoints[0]=web-insecure"
      - "traefik.http.routers.whoami.entrypoints[1]=web-secure"
      - "traefik.http.routers.whoami.tls=true"
      # Production ACME Cert
      - "traefik.http.routers.whoami.tls.certresolver=${ACME_DEFAULT_RESOLVER}"
      # Middleware list
      - "traefik.http.routers.whoami.middlewares=https-redirect,prefix-strip"
    networks:
      - ory_network
  # WHOAMI - Subdomain routed to custom service port
  portami:
    image: traefik/whoami
    labels:
      # Traefik-aware
      - "traefik.enable=true"
      # Subdomain routed directly to service at root path
      - "traefik.http.services.portami-svclb.loadbalancer.server.port=4040"
      - "traefik.http.routers.portami.service=portami-svclb"
      - "traefik.http.routers.portami.rule=Host(`${PORTAMI_SUBDOMAIN}.${SERVICE_DOMAIN}`)"
      # HTTP/HTTPS Ingress
      - "traefik.http.routers.portami.entrypoints[0]=web-insecure"
      - "traefik.http.routers.portami.entrypoints[1]=web-secure"
      - "traefik.http.routers.portami.tls=true"
      # Production ACME Cert
      - "traefik.http.routers.portami.tls.certresolver=${ACME_DEFAULT_RESOLVER}"
      # Middleware list
      - "traefik.http.routers.portami.middlewares=https-redirect"
    command:
      - "--port"
      - "4040"
    networks:
      - ory_network

networks:
  ory_network:
    external: true
