# whoami.yml
services:

  whoami:
    image: traefik/whoami
    env_file: 
      - path: .env
        required: true
    labels:
      # Traefik-aware
      - "traefik.enable=true"
      # Path-routed from "auth" subdomain
      - "traefik.http.routers.whoami.rule= Host(`${SERVICE_DOMAIN}`) && PathPrefix(`${WHOAMI_PUBLIC_PATH}`)"
      # Admin HTTPS Ingress
      - "traefik.http.routers.whoami.entrypoints=admin-secure"
      - "traefik.http.routers.whoami.tls=true"
      # Production ACME Cert
      - "traefik.http.routers.whoami.tls.certresolver=${ACME_DEFAULT_RESOLVER}"
      # Middleware list
      - "traefik.http.routers.whoami.middlewares=prefix-strip"
    networks:
      - ory_network
      
  consent:
    image: oryd/hydra:v${ORY_VERSION}
    container_name: ory-consent
    restart: unless-stopped
    env_file: 
      - path: .env
        required: true
    environment:
      - LOG_LEVEL=trace
    command: [
      perform, authorization-code, --port, "5555",
      --client-id, <SET ME>, --client-secret, <SET ME>,
      --endpoint, "https://${SERVICE_DOMAIN}${HYDRA_PUBLIC_PATH}", 
      --scope, openid, --scope, offline,
      --redirect, "https://${SERVICE_DOMAIN}${CONSENT_UI_PATH}/callback"
    ]
    networks:
      - ory_network
    labels:
      - "traefik.enable=true"
      # Consent App
      # Name-routed from subdomain
      - "traefik.http.routers.consent-ui.rule=Host(`${CONSENT_SUBDOMAIN}.${SERVICE_DOMAIN}`)"
      # Service LB for port forwarding
      - "traefik.http.services.consent-ui-svclb.loadbalancer.server.port=5555"
      - "traefik.http.routers.consent-ui.service=consent-ui-svclb"
      # HTTP/HTTPS ingress
      - "traefik.http.routers.consent-ui.entrypoints=web-insecure,web-secure"
      - "traefik.http.routers.consent-ui.tls=true"
      # Middlewares
      - "traefik.http.routers.consent-ui.middlewares=https-redirect,prefix-strip"
      # Production ACME cert
      - "traefik.http.routers.consent-ui.tls.certresolver=${ACME_DEFAULT_RESOLVER}"

  mailslurper:
    # Ory's MailSlurper implementation is broken, build from source
    build: https://github.com/mailslurper/mailslurper.git
    container_name: mailslurper
    env_file: 
      - path: .env
        required: true
    networks:
      - ory_network
    volumes:
      - ./extras/mailslurper:/app
    entrypoint: ["sh"]
    command: ["/app/entrypoint.sh"]
    labels:
      - "traefik.enable=true"
      # WEBMAIL UI
      # Name-routed from "webmail" subdomain on admin ports
      - "traefik.http.routers.mail.rule=Host(`${MAIL_SUBDOMAIN}.${SERVICE_DOMAIN}`)"
      # Service LB for port forwarding
      - "traefik.http.services.mail-svclb.loadbalancer.server.port=4436"
      - "traefik.http.routers.mail.service=mail-svclb"
      # Admin HTTPS Ingress
      - "traefik.http.routers.mail.entrypoints=admin-secure"
      - "traefik.http.routers.mail.tls=true"
      # Production ACME cert
      - "traefik.http.routers.mail.tls.certresolver=stg"
      # WEBMAIL API
      # Name-routed from "slurp" subdomain on admin ports
      - "traefik.http.routers.slurp.rule=Host(`${SLURP_SUBDOMAIN}.${SERVICE_DOMAIN}`)"
      # Service LB for port forwarding
      - "traefik.http.services.slurp-svclb.loadbalancer.server.port=4437"
      - "traefik.http.routers.slurp.service=slurp-svclb"
      # Admin HTTPS Ingress
      - "traefik.http.routers.slurp.entrypoints=admin-secure"
      - "traefik.http.routers.slurp.tls=true"
      # Production ACME cert
      - "traefik.http.routers.slurp.tls.certresolver=stg"
      # SMTP Service
      # Name-routed from "smtp" subdomain
      - "traefik.tcp.routers.smtp.rule=HostSNI(`${SMTP_SUBDOMAIN}.${SERVICE_DOMAIN}`)"
      # Service LB for port forwarding
      - "traefik.tcp.services.smtp-svclb.loadbalancer.server.port=1025"
      - "traefik.tcp.routers.smtp.service=smtp-svclb"
      # Custom SMTP ingress
      - "traefik.tcp.routers.smtp.entrypoints=tcp-smtp"
      - "traefik.tcp.routers.smtp.tls=true"
      # Production ACME cert
      - "traefik.tcp.routers.smtp.tls.certresolver=stg"

networks:
  ory_network:
    external: true
