version: '3.7'
services:
  kratos:
    image: oryd/kratos:v${ORY_VERSION}
    restart: unless-stopped
    env_file: 
      - path: .env
        required: true
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ory-pg:5432/${POSTGRES_KRATOS_DB}?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --watch-courier
    volumes:
      - ./ory/kratos:/etc/config/kratos
    networks:
      - ory_network
    labels:
      - "traefik.enable=true"
      # PUBLIC
      # Name-routed from subdomain
      - "traefik.http.routers.kratos-public.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.kratos-public.rule=PathPrefix(`${KRATOS_PUBLIC_PATH}`)"
      # Service LB for port forwarding
      - "traefik.http.services.kratos-public-svclb.loadbalancer.server.port=4433"
      - "traefik.http.routers.kratos-public.service=kratos-public-svclb"
      # HTTP/HTTPS ingress
      - "traefik.http.routers.kratos-public.entrypoints[0]=web-insecure"
      - "traefik.http.routers.kratos-public.entrypoints[1]=web-secure"
      - "traefik.http.routers.kratos-public.tls=true"
      # Middlewares
      - "traefik.http.routers.kratos-public.middlewares=https-redirect,prefix-strip"
      # Production ACME cert
      - "traefik.http.routers.kratos-public.tls.certresolver=prd"
      # ADMIN
      # Name-routed from "auth" subdomain
      - "traefik.http.routers.kratos-admin.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.kratos-admin.rule=PathPrefix(`${KRATOS_ADMIN_PATH}`)"
      # Service LB for port forwarding
      - "traefik.http.services.kratos-admin-svclb.loadbalancer.server.port=4434"
      - "traefik.http.routers.kratos-admin.service=kratos-admin-svclb"
      # HTTP/HTTPS ingress
      - "traefik.http.routers.kratos-admin.entrypoints[0]=web-insecure"
      - "traefik.http.routers.kratos-admin.entrypoints[1]=web-secure"
      - "traefik.http.routers.kratos-admin.tls=true"
      - "traefik.http.routers.kratos-admin.middlewares[1]=https-redirect"
      # Middlewares
      - "traefik.http.routers.kratos-admin.middlewares=https-redirect,prefix-strip"
      # Production ACME cert
      - "traefik.http.routers.kratos-admin.tls.certresolver=prd"

networks:
  ory_network:
    external: true

