version: '3.7'
services:

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v${ORY_VERSION}
    container_name: ory-self-service
    env_file: 
      - path: .env
        required: true
    environment:
      - KRATOS_PUBLIC_URL=https://${SERVICE_DOMAIN}${KRATOS_PUBLIC_PATH}
      - KRATOS_BROWSER_URL=https://${SERVICE_DOMAIN}${KRATOS_PUBLIC_PATH}
      - KRATOS_ADMIN_URL=https://${SERVICE_DOMAIN}:${ADMIN_PORT}${KRATOS_ADMIN_PATH}
      - HYDRA_ADMIN_URL=https://${SERVICE_DOMAIN}:${ADMIN_PORT}${HYDRA_ADMIN_PATH}
      - COOKIE_SECRET=${SELFSERVE_COOKIE_SECRET}
      - CSRF_COOKIE_NAME=${SELFSERVE_CSRF_COOKIE_NAME}
      - CSRF_COOKIE_SECRET=${SELFSERVE_CSRF_COOKIE_SECRET}
    networks:
      - ory_network
    restart: on-failure    
    labels:
      - "traefik.enable=true"
      # SELF SERVE UI
      # Name-routed from "auth" subdomain
      - "traefik.http.routers.self-serve.rule=Host(`${SERVICE_DOMAIN}`)" # Default route / UI view on domain
      # Service LB for port forwarding
      - "traefik.http.services.self-serve.loadbalancer.server.port=3000"
      - "traefik.http.routers.self-serve.service=self-serve"
      # HTTP/HTTPS ingress
      - "traefik.http.routers.self-serve.entrypoints=web-insecure,web-secure"
      - "traefik.http.routers.self-serve.tls=true"
      - "traefik.http.routers.self-serve.middlewares=https-redirect"
      # Production ACME cert
      - "traefik.http.routers.self-serve.tls.certresolver=${ACME_DEFAULT_RESOLVER}"

  ory-admin:
    image: dhiagharsallaoui/kratos-admin-ui:latest
    container_name: ory-admin
    restart: on-failure
    env_file: 
      - path: .env
        required: true
    environment:
      - KRATOS_PUBLIC_URL=https://${SERVICE_DOMAIN}${KRATOS_PUBLIC_PATH}
      - KRATOS_ADMIN_URL=https://${SERVICE_DOMAIN}:${ADMIN_PORT}${KRATOS_ADMIN_PATH}
      - HYDRA_PUBLIC_URL=https://${SERVICE_DOMAIN}${HYDRA_PUBLIC_PATH}
      - HYDRA_ADMIN_URL=https://${SERVICE_DOMAIN}:${ADMIN_PORT}${HYDRA_ADMIN_PATH}
    networks:
      - ory_network 
    labels:
      - "traefik.enable=true"
      # SELF SERVE UI
      # Name-routed from "auth" subdomain
      - "traefik.http.routers.ory-admin.rule=Host(`${ADMIN_SUBDOMAIN}.${SERVICE_DOMAIN}`)"
      # Service LB for port forwarding
      - "traefik.http.services.ory-admin-svclb.loadbalancer.server.port=3000"
      - "traefik.http.routers.ory-admin.service=ory-admin-svclb"
      # HTTP/HTTPS ingress
      - "traefik.http.routers.ory-admin.entrypoints=admin-secure"
      - "traefik.http.routers.ory-admin.tls=true"
      # Production ACME cert
      - "traefik.http.routers.ory-admin.tls.certresolver=stg"

networks:
  ory_network:
    external: true

