#! /bin/bash

if [ -n "$1" ]; then
    docker compose -f docker-compose-$1.yaml down $2
else
    echo "STOPPING STACK..."
    docker compose -f docker-compose-pg.yaml down
    docker compose -f docker-compose-ory.yaml down
    docker compose -f docker-compose-extras.yaml down
    docker compose -f docker-compose-net.yaml down
    echo "DONE."

    echo

    echo "REMOVING NETWORK..."
    docker network remove ory_network
    echo "DONE."
fi