#! /bin/bash

echo "CREATING NETWORK..."
docker network create ory_network
echo "DONE."

echo

echo "STARTING STACK..."
docker compose -f docker-compose-pg.yaml up -d
sleep 60
docker compose -f docker-compose-ory.yaml up -d
docker compose -f docker-compose-extras.yaml up -d
docker compose -f docker-compose-net.yaml up -d
echo "DONE."